version: "3.8"

services:
  mlflow_ui:
    image: python:3.10-slim
    working_dir: /app
    command: >
      bash -c "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:/app/mlruns"
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
