apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: mlflow:latest  # Replace with your actual image tag
          ports:
            - containerPort: 5000
          command: ["mlflow"]
          args:
            - ui
            - --host=0.0.0.0
            - --port=5000
            - --backend-store-uri
            - file:/app/mlruns
          volumeMounts:
            - name: mlflow-data
              mountPath: /app/mlruns
      volumes:
        - name: mlflow-data
          hostPath:
            path: /mnt/mlflow-data
            type: DirectoryOrCreate
