apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 5000  # Optional; Kubernetes will auto-assign if omitted

