apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-model-server
  template:
    metadata:
      labels:
        app: mlflow-model-server
    spec:
      containers:
        - name: mlflow-model
          image: mlflow-model:v1
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_URI
              value: runs:/281eaf6510f84fb18e0d60410c14c000/iris_model
            - name: MLFLOW_TRACKING_URI
              value: http://10.100.198.240:5000
