apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-model-server
  template:
    metadata:
      labels:
        app: mlflow-model-server
    spec:
      containers:
        - name: mlflow-model
          image: yogeshbhatt1000/mlflow-model:latest
          ports:
            - containerPort: 5000
          env:
            - name: MODEL_URI
              value: runs:/9095deddd60a4baba872f8afaa4e894b/iris_model  # Replace dynamically
            - name: MLFLOW_TRACKING_URI
              value: http://10.110.234.157:5000  # Replace dynamically
          command: ["sh", "-c"]
          args:
            - mlflow models serve -m $MODEL_URI --host 0.0.0.0 --port 5000
