apiVersion: v1
kind: Service
metadata:
  name: mlflow-model-server
spec:
  type: ClusterIP
  selector:
    app: mlflow-model-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
